### ISSUE TITLE
Replace our test framework with Jasmine

### ISSUE THREAD

**Issue by kristiandupont** [realm/realm-js#1205]
Currently, our tests run with a homewritten assertion framework, kindof through Jasmine for Node. We should use Jasmine everywhere and get rid of asserts.js

### TODO
- [ ] Move the files from `/tests/shared/js` to `/tests/shared/spec` and subfolders thereof.
- [ ] Don't export functions from the modules, but call Jasmine `describe(` and `it(` directly.
- [ ] Replace the use of `TestCase.*` assertions (loaded from `./tests/shared/js/asserts.js` with [Jasmine expections](https://jasmine.github.io/2.5/introduction.html#section-Expectations).
- [ ] Replace the use of promises `tests/react-test-app/tests/index.js` in favor of a [Jasmine Reporter](https://jasmine.github.io/2.5/custom_reporter.html).

**Comment by kraenhansen** [comment]
Closing in favor of https://github.com/realm/realm-js/issues/1929.
