### ISSUE TITLE
Problems Identified With Release Process

### ISSUE THREAD

**Issue by bigfish24** [realm/realm-js#1217]
Based on the meeting this morning these were the notes of issues identified in the process:

- [x] Run npm install on repo first is not in the list of step
- [ ] CI not running all tests with realm-js and instead the release script runs additional ones (such as RealmJS and Android tests)
- [x] RealmJS tests use JSContext which doesn't have access to REST APIs causing specific tests to fail (see #1215)
- [ ] weird behavior with ReactNative tests is never tracked so it is not possible to address
- [ ] general impression that we heavily rely on Yavor when things go wrong (#1257)
- [ ] npm 5.3.0 isn’t working for releases (#1256)
- [ ] publishing binaries is a second step to main publishing which creates time window when the npm install will resort to compiling (not clear if this will work with Windows)
- [ ] node-gyp fails silently on install (not observed but noted by me that this has appeared lately)
- [ ] no standard way to test against ROS (general problem across all repos)
- [ ] can't publish binaries first, because this relies on object store public to be newer version
- [ ] manually have to run Android simulator instead of full automation (#1237)
- [ ] XPC cocoa failures observed (https://github.com/realm/realm-js-private/issues/314)

Sporadic errors observed when running `publish.sh`:
```
[08/16/2017, 14:33:30] <END>   Initializing Packager (1303ms)
~/repositories/realm/realm-js/tests/react-test-app/ios ~/repositories/realm/realm-js/tests/react-test-app ~/repositories/realm/realm-js
-e:1:in `<main>': undefined method `[]' for nil:NilClass (NoMethodError)
scripts/test.sh: line 64:  9104 Killed: 9               sh ./object-server-for-testing/start-object-server.command  (wd: ~/repositories/realm/realm-js)
scripts/test.sh: line 64:  9248 Killed: 9               ./node_modules/react-native/packager/packager.sh
      9249                       | tee "$PACKAGER_OUT"  (wd: ~/repositories/realm/realm-js/tests/react-test-app)
npm ERR! Test failed.  See above for more details.
````

```
RealmReactTests.m:245: error: -[UserTests testRegisterUser] : Error: Error TypeError: Network request failed was not expected
```
This second error appears for all tests that use `fetch`

cc @kristiandupont @bmunkholm we should try to break these down into specific issues and set aside time to fix them

**Comment by kneth** [comment]
See #1215

**Comment by kneth** [comment]
Observation by @fealebenpae:

It appears that there is a small window between pushing the `Bump version` commit and pushing the version tag to GitHub. If this window is sufficiently large, Jenkins will start building from the commit push before the tag has been pushed which will result it in publishing to `static.realm.io` with a commit sha appended to the version. I fixed this instance by renaming the folder on s3, but we should either document the need to push the commit and tag at the same time, or otherwise revise the process so that we are not dependent on timing
