### ISSUE TITLE
Add support for Arrays of primitives

### ISSUE THREAD

**Issue by kneth** [realm/realm-js#1229]
## Description

Related to realm/product#59

## TODO

* [ ] Update to new object store (waiting for https://github.com/realm/realm-object-store/pull/512)
* [ ] Add changelog entry
* [ ] Schema: translate JS schema to object store
* [ ] Creating objects
* [ ] Tests

**Comment by kneth** [comment]
I close this issue. @tgoyne has implemented, tested and documented it.
