### ISSUE TITLE
Improvements to the test harness

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-js#1929]
## Goals

Realm Studio has [been experiencing regressions](https://github.com/realm/realm-js/issues/1864) and I believe improvements to the test harness will help fix this:
- [x] We should run all tests from multiple environments:
  - [x] Node.js
  - [ ] Electron on MacOS
  - [x] Electron on Linux
  - [ ] Electron on Windows
  - [x] React Native on Android
  - [x] React Native on iOS
  - [ ] React Native in debug mode (runs in Chrome)
- [x] We should use mocha instead of jasmine, as we are using this everywhere else and not rely on our own assertion library but instead use chai.
- [ ] ~The server should be started and stopped for each test to prevent cross-talking between tests.~
- [ ] Write tests of installing Realm from scratch into the latest version of various environments (should not fail the build if an issue is found):
  - [ ] Electron: Install the latest available version of Electron and `electron-builder`, install the Realm JS package and use Realm JS for something simple.
  - [ ] React Native: Install the latest version of `react-native` CLI, create an app, install the Realm JS package, run `react-native link realm`, build the app and use Realm JS for something simple.
- [x] Use TypeScript when implementing the test suite.

## Version of Realm and Tooling

- Realm JS SDK Version: 2.13.0
- Node or React Native: N/A
- Client OS & Version: N/A
- Which debugger for React Native: N/A

**Comment by kraenhansen** [comment]
Putting this on hold for now - but I've made a lot of progress on this with https://github.com/realm/realm-js/tree/kh/integration-tests/integration-tests it is basically setting up the test harness for Node.js, Electron and React Native - but the tests needs to be refactored / rewritten to use mocha in a less complicated way.

**Comment by nirinchev** [comment]
The CI repo exposes a `withRos` function that spins up a ROS instance and gives you address to connect to. If the tests are written in a way that the entire test suite can be run against a single running instance (i.e. they don't rely on controlling the lifetime or configuration of that instance), then it should be fine to use.

**Comment by kraenhansen** [comment]
A lot of code changed with https://github.com/realm/realm-js/pull/3690 and this issue mentions ROS (now deprecated). As such I think it's safe to close this and create a new issue if / when we want to make progress on this.
