### ISSUE TITLE
Merge Stitch and Realm SDKs - Realm Web - Phase 1

### ISSUE THREAD

**Issue by RealmBot** [realm/realm-js#2699]
## Tasks
* [x] Setup multi package repository.
* [x] Implement first draft of TypeScript interfaces shared across Realm JS and Realm Web.
* [x] Implement a shared network transport between Realm JS and Realm Web (realm-network-transport).
* [x] Implement basics of authentication (anon + user-pass credentials, authenticated network transport).
* [x] Setup the "realm-web-integration-tests" package using WebPack, Puppeteer & Mocha Remote.
* [x] Implement basics of functions (call a function with an authenticated user)
* [x] Use eslint instead of the deprecated tslint.
* [x] Implement a couple of credentials for authentication providers:
  * [x] Anonymous
  * [x] API Key
  * [x] Email & password (formerly known as username & password)
* [x] Implement standard service clients on top of functions:
  * [x] Remote MongoDB
  * [x] HTTP

Below tasks has been moved to move to "phase 2":

* [ ] Implement auth-provider clients:
  * [ ] Email & password (reset password, confirm email, etc.) _[implemented, but missing passing e2e tests]_
  * [ ] API keys (enable, disable, list, get, create, etc.) _[implemented, but missing passing e2e tests]_
* [ ] Implement more credentials for authentication providers:
  * [ ] Facebook
  * [ ] Google
  * [ ] Custom JWT
  * [ ] Apple Sign In
  * [ ] Functions
* [ ] Linking a current user with another identity
* [ ] Retrieve a users custom data _[implemented, but missing passing e2e tests]_
* [ ] Ensure xjson is used to serialize requests and parse responses where appropriate
* [ ] Persist logged in users in the browsers local storage.
* [ ] Revisit and align Remote MongoDB API with the Node.js driver.
* [ ] Upgrade from Mocha 5 to latest (and use "modules": "es6" in tsconfig.jsons)
* [ ] Add the the missing credentials types to app.d.ts.
* [ ] Implement fetching the location (baseURL) of where an app is running in the Stitch production environment.
* [ ] Send device information on authentication requests.

Details of above subtasks are described in this [doc](https://docs.google.com/document/d/1iD9ujY76BWVUOdN7rRH4XyPF9hHxx48RcGc-ZaQPyII/edit#heading=h.5zfqez3rx85o)

**Comment by RealmBot** [comment]
➤ Kræn Hansen commented:

[~drew.dipalma] can you help me understand what authentication providers are important / needed for an early beta release of the Realm Web JS SDK?
It seems to me that "Apple Sign In" is not that important for web and Facebook + Google is harder for me to setup integration tests for.
Also: Do we need / want users to be authenticated across visits to the same web-app?

**Comment by RealmBot** [comment]
➤ Drew DiPalma commented:

Custom Authentication and email/password are the most important providers, but all are required for the public beta in June. 

What do you mean by "Do we need / want users to be authenticated across visits to the same web-app" – I would expect authentication across sessions to work the same as it does for Stitch today?

**Comment by RealmBot** [comment]
➤ Kræn Hansen commented:

Thanks.

I havn't yet built a web-app using the current Stitch SDK, so I don't know by heart, what the behaviour of current SDK is.
I found some code responsible for storing and retrieving the user ( https://github.com/mongodb/stitch-js-sdk/blob/master/packages/core/sdk/src/auth/internal/models/StoreAuthInfo.ts ) and I believe this will suffice to help me understand the current behaviour.
