### ISSUE TITLE
Realm Web & JS: Aligning the APIs (a bit more)

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-js#3256]
## Goals
Alignment of the APIs even more: The same API no matter if Realm JS or Realm Web is used.

## TODO:
* [ ] Go through the "v10 API" spreadsheet once again to create more TODOs in this issue.
* [x] Realm Web: Remove the `services` property from instances of `App`.
* [x] Realm Web: Expose the `getApp` function on `App` as well as the package as a whole.
* [x] Realm JS: Rename static `App` member to `getCachedApp` to `getApp`. (see https://github.com/realm/realm-js/pull/3281)
