### ISSUE TITLE
Node release checklist

### ISSUE THREAD

**Issue by alazier** [realm/realm-js#638]
- [ ] support building node for linux/mac using node-pre-gyp #636
- [ ] get ci setup to test node for linux and mac #637
- [ ] get react-native working reliably on ci
- [ ] sync example
- [ ] support building for linux with sync disabled

**Comment by bigfish24** [comment]
I am going to transform this into a milestone and update the PE milestone as well
